<?php

class PluginClearsignaldiagFormatter {

    /**
     * Build an HTML-formatted summary suitable for GLPI ticket follow-ups.
     */
    public static function buildTicketSummary(array $result): string {
        $target = htmlspecialchars($result['target']['input'] ?? 'unknown', ENT_QUOTES, 'UTF-8');
        $date = date('Y-m-d H:i:s');

        $lines = [];
        $lines[] = '<h3>ClearSignal Diagnostics Report</h3>';
        $lines[] = '<p><strong>Date:</strong> ' . $date . '<br>';
        $lines[] = '<strong>Target:</strong> ' . $target . '</p>';

        $checks = $result['checks'] ?? [];
        if (!is_array($checks) || count($checks) === 0) {
            $lines[] = '<p><em>No checks returned.</em></p>';
            return implode("\n", $lines);
        }

        $lines[] = '<table style="border-collapse:collapse; width:100%; margin-bottom:10px;">';
        $lines[] = '<tr style="background:#f0f0f0;"><th style="padding:4px 8px; text-align:left; border:1px solid #ddd;">Check</th><th style="padding:4px 8px; text-align:left; border:1px solid #ddd;">Result</th></tr>';
        foreach ($checks as $check) {
            $name = htmlspecialchars($check['name'] ?? 'Unknown', ENT_QUOTES, 'UTF-8');
            $summary = htmlspecialchars($check['summary'] ?? 'No summary', ENT_QUOTES, 'UTF-8');
            $icon = self::statusIndicator($check['summary'] ?? '');
            $lines[] = '<tr><td style="padding:4px 8px; border:1px solid #ddd;">' . $name . '</td><td style="padding:4px 8px; border:1px solid #ddd;">' . $icon . ' ' . $summary . '</td></tr>';
        }
        $lines[] = '</table>';

        $causes = [];
        $fixes = [];
        foreach ($checks as $check) {
            if (!empty($check['likely_root_cause'])) {
                $causes[] = htmlspecialchars($check['likely_root_cause'], ENT_QUOTES, 'UTF-8');
            }
            if (!empty($check['recommended_fix'])) {
                $fixes[] = htmlspecialchars($check['recommended_fix'], ENT_QUOTES, 'UTF-8');
            }
        }

        if ($causes) {
            $lines[] = '<p><strong>Likely Root Cause:</strong></p><ul>';
            foreach (array_unique($causes) as $cause) {
                $lines[] = '<li>' . $cause . '</li>';
            }
            $lines[] = '</ul>';
        }

        if ($fixes) {
            $lines[] = '<p><strong>Recommended Fix:</strong></p><ul>';
            foreach (array_unique($fixes) as $fix) {
                $lines[] = '<li>' . $fix . '</li>';
            }
            $lines[] = '</ul>';
        }

        $lines[] = '<hr><p style="font-size:0.8em; color:#888;">Generated by ClearSignal Diagnostics plugin</p>';

        return implode("\n", $lines);
    }

    /**
     * Build a plain-text summary (for contexts that don't support HTML).
     */
    public static function buildPlainTextSummary(array $result): string {
        $lines = [];
        $lines[] = '=== ClearSignal Diagnostics Report ===';
        $lines[] = 'Date: ' . date('Y-m-d H:i:s');
        $lines[] = 'Target: ' . ($result['target']['input'] ?? 'unknown');
        $lines[] = '';

        $checks = $result['checks'] ?? [];
        if (!is_array($checks) || count($checks) === 0) {
            $lines[] = 'No checks returned.';
            return implode("\n", $lines);
        }

        foreach ($checks as $check) {
            $lines[] = '  [' . ($check['name'] ?? 'Unknown') . '] ' . ($check['summary'] ?? 'No summary');
        }

        $causes = [];
        $fixes = [];
        foreach ($checks as $check) {
            if (!empty($check['likely_root_cause'])) {
                $causes[] = '  - ' . $check['likely_root_cause'];
            }
            if (!empty($check['recommended_fix'])) {
                $fixes[] = '  - ' . $check['recommended_fix'];
            }
        }

        if ($causes) {
            $lines[] = '';
            $lines[] = '--- Likely Root Cause ---';
            foreach (array_unique($causes) as $line) {
                $lines[] = $line;
            }
        }

        if ($fixes) {
            $lines[] = '';
            $lines[] = '--- Recommended Fix ---';
            foreach (array_unique($fixes) as $line) {
                $lines[] = $line;
            }
        }

        $lines[] = '';
        $lines[] = '=== End of Report ===';
        return implode("\n", $lines);
    }

    private static function statusIndicator(string $summary): string {
        $lower = strtolower($summary);
        if (str_contains($lower, 'fail') || str_contains($lower, 'error') || str_contains($lower, 'stopped') || str_contains($lower, 'no ')) {
            return '&#10060;';
        }
        if (str_contains($lower, 'warning') || str_contains($lower, 'disagree') || str_contains($lower, 'possible') || str_contains($lower, 'multiple')) {
            return '&#9888;';
        }
        return '&#9989;';
    }
}
